version: 0.0
os: linux
files:
  - source: /
    destination: /opt/libros

permissions:
  - object: /opt/libros
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
hooks:
  BeforeInstall:
    - location: stop_server.sh
      runas: root
  AfterInstall:
    - location: install_dependencies.sh
      runas: root
  ApplicationStart:
    - location: start_server.sh
      runas: root
  environment:
    variables:
      - name: DB_NAME
        value: "ssm:/DB/NAME"
      - name: DB_USERNAME
        value: "ssm:/DB/USERNAME"
      - name: DB_PASSWORD
        value: "ssm:/DB/PASSWORD"
