version: 0.0
os: linux
files:
  - source: /
    destination: /opt/libros

permissions:
  - object: /opt/libros
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: install_dependencies_eks.sh
      runas: root
  ApplicationStart:
    - location: kube.sh
      runas: root
  ValidateService:
    - location: validate.sh
      runas: root