version: 0.2

env:
  parameter-store:
    DB_NAME: "/DB/NAME"
    DB_USERNAME: "/DB/USERNAME"
    DB_PASSWORD: "/DB/PASSWORD"
    IMAGE_REPO_NAME: "/IMAGE/REPO/NAME"
    IMAGE_TAG: "/IMAGE/TAG"
    DOCKERHUB_USERNAME: "/DOCKERHUB/USERNAME"
    DOCKERHUB_PASSWORD: "/DOCKERHUB/PASSWORD"
    REGISTRY_URL: "/REGISTRY/URL"

phases:
  install:
    runtime-versions:
      java: corretto21  # Establece la versión de Java a utilizar
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Compiling the project..."
  build:
    commands:
      - echo "Running tests..."
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - scripts/*.sh
    - appspec.yml
    - deployment.yml
    - k8s-cluster.yml
  discard-paths: yes  # Descarta las rutas de los archivos al especificar los artefactos

cache:
  paths:
    - '/root/.m2/**/*'
