version: 0.2

env:
  parameter-store:
    DB_NAME: "/DB/NAME"
    DB_USERNAME: "/DB/USERNAME"
    DB_PASSWORD: "/DB/PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto17  # Establece la versión de Java a utilizar
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven
  pre_build:
    commands:
      - echo "Compiling the project..."
      - mvn compile  # Compila el proyecto antes de ejecutar las pruebas
      - echo DB_NAME=${DB_NAME} >> .env
      - echo DB_USERNAME=${DB_USERNAME} >> .env
      - echo DB_PASSWORD=${DB_PASSWORD} >> .env
  build:
    commands:
      - echo "Running tests..."
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar  # Especifica los archivos JAR como artefactos de salida
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes  # Descarta las rutas de los archivos al especificar los artefactos

cache:
  paths:
    - '/root/.m2/**/*'
